from fastapi import FastAPI, HTTPException, Request
import hashlib
import hmac
import os
import time
from pydantic import BaseModel
from typing import Dict, Optional
from queen.apiary_lease_manager import LeaseContract, LeaseRequest

# --- Kytin Swarm: Queen Node Validator ---
# Role: Sovereign Gateway Authorization & Decentralized Relayer
# Platform: NVIDIA RTX 6000 Ada
# Architecture: Any Queen can relay for any Princess (Blind Courier Mode)

app = FastAPI(title="Kytin Sovereign Gateway — Decentralized Relayer")

# HIVE_SECRET must match the secret flashed onto every Sting in the network
HIVE_SECRET = os.getenv("HIVE_SECRET", "GENESIS_LITE_SECURE_KEY_992")
QUEEN_ID = os.getenv("QUEEN_ID", "QUEEN_PRIMARY")

# --- MASTER MANIFEST DIRECTIVES ---
# 1. Strict Memory Fencing: Reserve 16GB VRAM for the Integrated Heart (Genesis Node)
VRAM_FENCING_RESERVE_GB = 16 
# 2. P2P Discovery Priority over DNS
P2P_DISCOVERY_PRIORITY = True
# 3. Relay Rate: 0.5 RSN per unit (Managed by apiary_lease_manager)

# Swarm Registry: Stores Princess IDs and their authorization state
swarm_registry: Dict[str, dict] = {}

# Relay Ledger: Tracks transactions relayed and Nectar earned
relay_ledger: list = []

# Lease Manager: Automates the $RSN$ Nectar Tax
lease_manager = LeaseContract(queen_id=QUEEN_ID)


class AuthRequest(BaseModel):
    princess_id: str      # The Orin Serial Number
    challenge: str        # The random string sent by the Princess daemon
    signature: str        # The hash generated by the physical Sting
    intent: str           # e.g., "MAINNET_BROADCAST" or "SKILL_SYNC"

class RenewalRequest(BaseModel):
    princess_id: str
    amount: float
    signature: str


class RelayPacket(BaseModel):
    princess_id: str
    session_hash: str
    gateway_token: str
    signed_tx: str        # The immutable, Sting-signed transaction hex
    nectar_bounty: float  # Micro-toll reward in $RESIN
    ttl: int              # Time-to-live in seconds
    timestamp: int


@app.post("/apiary/lease/request")
async def request_lease(request: LeaseRequest):
    """
    Princess Lease Proposal: Evaluate and secure network access.
    """
    # Simulated current load check
    current_load = 0.45 
    
    result = lease_manager.evaluate_lease(request, current_load)
    if result["status"] == "REJECTED":
        raise HTTPException(status_code=403, detail=result["reason"])
        
    return result


@app.post("/authorize_princess")
async def authorize_princess(auth: AuthRequest):
    """
    Verifies the physical State-Lock proof from any Princess node.
    Any Queen in the Global Intelligence Network can authorize any Princess.
    """
    print(f"[*] Auth request from Princess: {auth.princess_id}")

    # Zero-Trust: Recreate the hash using our shared HIVE_SECRET
    expected_payload = auth.challenge + HIVE_SECRET
    verified_hash = hashlib.sha256(expected_payload.encode()).hexdigest()

    if auth.signature != verified_hash:
        print(f"[!] CRITICAL: Invalid signature from {auth.princess_id}. Dropping.")
        raise HTTPException(status_code=403, detail="State-Lock Verification Failed")

    # Update the Swarm Registry
    swarm_registry[auth.princess_id] = {
        "status": "AUTHORIZED",
        "last_seen": int(time.time()),
        "last_intent": auth.intent,
        "authorized_by": QUEEN_ID
    }

    # Grant a gateway token for subsequent relay requests
    gateway_token = "KYTIN_SESSION_" + hashlib.md5(auth.signature.encode()).hexdigest()[:10]
    print(f"[+] Princess {auth.princess_id} authorized. Token: {gateway_token}")
    
    return {
        "status": "SUCCESS",
        "message": "Sovereign Tunnel Active",
        "gateway_token": gateway_token,
        "queen_id": QUEEN_ID
    }


@app.post("/relay_transaction")
async def relay_transaction(packet: RelayPacket):
    """
    Blind Courier Relay: Accept a State-Locked transaction from any 
    authorized Princess and broadcast it to the mainnet.
    
    The Queen cannot read the underlying logic or strategy —
    it only sees the signed transaction hex and submits it.
    The Nectar Bounty is claimed upon successful relay.
    """
    # 1. Verify the Princess is authorized and has an active lease
    princess = swarm_registry.get(packet.princess_id)
    if not princess or princess["status"] != "AUTHORIZED":
        raise HTTPException(status_code=403, detail="Princess not authorized")

    if not lease_manager.check_lease_validity(packet.princess_id):
        # Implementation of "The Cold Shoulder"
        print(f"[-] THE COLD SHOULDER: Severing tunnel for {packet.princess_id} (No active lease)")
        swarm_registry[packet.princess_id]["status"] = "LOCKED"
        raise HTTPException(status_code=402, detail="INSUFFICIENT_NECTAR_OR_LEASE_EXPIRED")

    # 2. Verify the packet hasn't expired
    age = int(time.time()) - packet.timestamp
    if age > packet.ttl:
        raise HTTPException(status_code=408, detail="Relay packet expired (TTL exceeded)")

    # 3. Submit the signed_tx to the blockchain
    # In production: call the local blockchain node's RPC (e.g., Solana sendTransaction)
    print(f"[*] BLIND RELAY: Submitting signed TX from Princess {packet.princess_id}...")
    print(f"    TX Hex (first 40 chars): {packet.signed_tx[:40]}...")
    print(f"    Nectar Bounty: {packet.nectar_bounty} RESIN")
    
    # Auto-Billing: Decrement $RSN$ balance
    lease_manager.billing_event(packet.princess_id)

    # Simulated mainnet broadcast
    tx_hash = hashlib.sha256(packet.signed_tx.encode()).hexdigest()[:16]

    # 4. Record the relay in our ledger
    relay_record = {
        "princess_id": packet.princess_id,
        "tx_hash": tx_hash,
        "nectar_earned": packet.nectar_bounty,
        "relayed_at": int(time.time()),
        "queen_id": QUEEN_ID
    }
    relay_ledger.append(relay_record)

    print(f"[+] TX relayed successfully. Hash: {tx_hash}")
    print(f"[+] Nectar Bounty claimed: {packet.nectar_bounty} RESIN")

    return {
        "status": "RELAYED",
        "tx_hash": tx_hash,
        "queen_id": QUEEN_ID,
        "nectar_claimed": packet.nectar_bounty
    }


@app.get("/swarm_status")
async def get_swarm_status():
    """Snapshot of all active Princess nodes authorized by this Queen."""
    return swarm_registry


@app.get("/relay_ledger")
async def get_relay_ledger():
    """Returns the history of relayed transactions and Nectar earnings."""
    total_nectar = sum(r["nectar_earned"] for r in relay_ledger)
    return {
        "queen_id": QUEEN_ID,
        "total_relays": len(relay_ledger),
        "total_nectar_earned": total_nectar,
        "recent_relays": relay_ledger[-20:]  # Last 20 relays
    }


@app.get("/tx_status/{tx_id}")
async def get_tx_status(tx_id: str):
    """
    Transaction status endpoint for the Princess Transaction Monitor.
    Allows the Orin to poll for ledger confirmation and trigger Sting LCD updates.
    """
    for record in relay_ledger:
        if record["tx_hash"] == tx_id:
            # In production: query the local blockchain node for finalization status
            return {
                "tx_id": tx_id,
                "status": "confirmed",
                "queen_id": record["queen_id"],
                "relayed_at": record["relayed_at"]
            }
    
    return {"tx_id": tx_id, "status": "pending"}


@app.get("/lease/status/{princess_id}")
async def get_lease_status(princess_id: str):
    """Returns the current healthy/expiry status of a Princess's lease."""
    status = lease_manager.get_lease_status(princess_id)
    if not status:
        raise HTTPException(status_code=404, detail="Lease not found")
        
    # Calculate percentage for LRA logic
    # In a real system, we'd compare against initial duration
    # Here we simulate a 60-minute window for the 'pct' calculation
    status["time_remaining_pct"] = status["time_remaining_sec"] / (60 * 60) 
    
    return status


@app.post("/lease/renew")
async def renew_lease(renew: RenewalRequest):
    """
    Handle autonomous renewal requests from Princess nodes.
    Requires a valid Sting signature.
    """
    # Verify signature (Re-using some logic for demo purposes)
    # In production, this would verify the $RSN$ transaction proof
    if not renew.signature:
         raise HTTPException(status_code=403, detail="Signature missing")

    success = lease_manager.extend_lease(renew.princess_id, renew.amount)
    if not success:
        raise HTTPException(status_code=400, detail="Failed to extend lease")
        
    status = lease_manager.get_lease_status(renew.princess_id)
    return {
        "status": "EXTENDED",
        "new_expiry": status["expiry_timestamp"],
        "new_balance": status["rsn_balance"]
    }


if __name__ == "__main__":
    import uvicorn
    # The Queen listens on a secure local network or a private P2P tunnel
    uvicorn.run(app, host="0.0.0.0", port=8888)
